sudo: required
language: generic
services: docker
env:
  - HHVM_VERSION=4.41-latest
  - HHVM_VERSION=4.56-latest
  - HHVM_VERSION=4.62-latest
  # - HHVM_VERSION=4.63-latest (skipped)
  - HHVM_VERSION=4.64-latest


install:
- docker pull hhvm/hhvm:$HHVM_VERSION
script:
- docker run --rm -w /var/source -v $(pwd):/var/source hhvm/hhvm:$HHVM_VERSION ./.travis.sh
